apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: mostwanted0001/microservicio-spring:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  selector:
    app: lab-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
